
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Siti Afiyah
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNoResi = new javax.swing.JTextField();
        txtNoPol = new javax.swing.JTextField();
        rdMobil = new javax.swing.JRadioButton();
        rdMotor = new javax.swing.JRadioButton();
        TanggalKeluar = new com.toedter.calendar.JDateChooser();
        TanggalMasuk = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNama = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtJumlahHari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("NOPOL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 290, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Kendaraan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 340, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Masuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 380, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 540, 100, 30);
        getContentPane().add(txtNoResi);
        txtNoResi.setBounds(200, 250, 240, 30);
        getContentPane().add(txtNoPol);
        txtNoPol.setBounds(200, 290, 240, 30);

        buttonGroup1.add(rdMobil);
        rdMobil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdMobil.setText("Mobil");
        rdMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMobilActionPerformed(evt);
            }
        });
        getContentPane().add(rdMobil);
        rdMobil.setBounds(210, 340, 90, 23);

        buttonGroup1.add(rdMotor);
        rdMotor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdMotor.setText("Motor");
        getContentPane().add(rdMotor);
        rdMotor.setBounds(320, 340, 80, 23);
        getContentPane().add(TanggalKeluar);
        TanggalKeluar.setBounds(200, 420, 240, 30);
        getContentPane().add(TanggalMasuk);
        TanggalMasuk.setBounds(200, 380, 240, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Penitipan Mobil dan Motor Makmur Jaya");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 20, 670, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jln. Danau Ranau Sawojajar Malang");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 70, 320, 30);

        jPanel2.setBackground(new java.awt.Color(180, 177, 177));
        jPanel2.setLayout(null);

        txtNama.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jPanel2.add(txtNama);
        txtNama.setBounds(100, 40, 70, 40);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Selamat Datang");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 10, 160, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 10, 250, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 120);

        jLabel8.setFont(new java.awt.Font("SketchFlow Print", 1, 18)); // NOI18N
        jLabel8.setText("ISIKAN DATA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 150, 180, 30);

        Save.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(70, 610, 100, 40);

        Clear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(290, 610, 100, 40);

        Delete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(480, 610, 100, 40);

        Print.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print);
        Print.setBounds(790, 610, 100, 40);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "NamaPetugas", "NoResi", "NoPol", "JenisKendaraan", "TanggalMasuk", "TanggalKeluar", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setHeaderValue("id");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 210, 610, 360);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tanggal Keluar");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 420, 100, 30);

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtHarga);
        txtHarga.setBounds(200, 540, 240, 30);

        txtJumlahHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahHariActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlahHari);
        txtJumlahHari.setBounds(200, 460, 240, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Jumlah Hari");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 460, 100, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Lihat Harga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 500, 100, 30);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 610, 100, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("No Resi");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 250, 120, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 120, 1100, 20);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(940, 610, 100, 40);

        setBounds(0, 0, 1109, 721);
    }// </editor-fold>//GEN-END:initComponents

    private void rdMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMobilActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        //String tanggal = ((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String masuk = dateFormat.format(TanggalMasuk.getDate());
        String keluar = dateFormat.format(TanggalKeluar.getDate());
        String JK = "";

          if (rdMobil.isSelected()){
                JK = "Mobil";
            }else{
                JK = "Motor";
            }
        
        if (
            txtNama.getText().equals("") ||
            txtNoResi.getText().equals("") ||
            txtNoPol.getText().equals("")||
            JK.equals("")||
                masuk.equals("") ||
                keluar.equals("") ||
            txtHarga.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL ="INSERT INTO `tb_data`(`id`,`NamaPetugas`, `NoResi`, `NoPol`, `JenisKendaraan`, `TanggalMasuk`, `TanggalKeluar`, `Harga`)" 
                    + "VALUES(NULL,'"+txtNama.getText()+"','"+txtNoResi.getText()+"','"+txtNoPol.getText()+"','"+JK+"','"+masuk+"',"
                    + "'"+keluar+"','"+txtHarga.getText()+"')";

            int status = KoneksiDB.execute(SQL);
            
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
         int baris = tblData.getSelectedRow();
        if(baris != -1){
            String id = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_data WHERE id='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        MessageFormat header = new MessageFormat("Data Penitipan Mobil dan Motor Makmur Jaya");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
         txtNama.setText("");
         txtNoResi.setText("");
         txtNoPol.setText("");
         buttonGroup1.clearSelection();
         txtJumlahHari.setText("");
         txtHarga.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void txtJumlahHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahHariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int hitung = Integer.parseInt(txtJumlahHari.getText());
        int jumlah = 0;
        
        jumlah = hitung*3000;
        txtHarga.setText(String.valueOf(jumlah));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectData();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String user1 = Login.user;
       txtNama.setText(user1);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris =tblData.getSelectedRow();
        if (baris != -1){
           
           txtNama.setText(tblData.getValueAt(baris,1).toString());
           txtNoResi.setText(tblData.getValueAt(baris,2).toString());
           txtNoPol.setText(tblData.getValueAt(baris,3).toString());
           
           String JK = tblData.getValueAt(baris,4).toString();
            if (JK.equals("Laki-laki")){
                rdMobil.setSelected(true);
            }else {
                rdMotor.setSelected(true);
            }
           
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String masuk = tblData.getValueAt(baris,5).toString();
            Date tgl;
            try {
                tgl = dateFormat.parse(masuk);
                TanggalMasuk.setDate(tgl);
            }catch (ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null,ex);
            }
            
            String keluar = tblData.getValueAt(baris,6).toString();
            Date tgl1;
            try {
                tgl1 = dateFormat.parse(keluar);
                TanggalKeluar.setDate(tgl1);
            }catch (ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null,ex);
            }
            
            
            txtHarga.setText(tblData.getValueAt(baris,7).toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Print;
    private javax.swing.JButton Save;
    private com.toedter.calendar.JDateChooser TanggalKeluar;
    private com.toedter.calendar.JDateChooser TanggalMasuk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdMobil;
    private javax.swing.JRadioButton rdMotor;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlahHari;
    private javax.swing.JLabel txtNama;
    private javax.swing.JTextField txtNoPol;
    private javax.swing.JTextField txtNoResi;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"id","NamaPetugas","NoResi","NoPol","JenisKendaraan","TanggalMasuk","TanggalKeluar","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_data";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String NamaPetugas = rs.getString(2);
                String NoResi = rs.getString(3);
                String NoPol = rs.getString(4);
                String JenisKendaraan = "";
                if("Mobil".equals(rs.getString(5))){
                    JenisKendaraan = "Mobil";
                }else {
                    JenisKendaraan = "Motor";
                }
                String TanggalMasuk = rs.getString(6);
                String TanggalKeluar = rs.getString(7);
                String Harga = rs.getString(8);

                String data[] = {id,NamaPetugas,NoResi,NoPol,JenisKendaraan,TanggalMasuk,TanggalKeluar,Harga};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
           // Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);//To change body of generated methods, choose Tools | Templates.
    }
}
